baseURL=                    "http://dongjian.github.io/"
disqusShortname = "dongjian"

googleAnalytics="UA-50476358-2"

hasCJKLanguage=false

languageCode = "zh-CN"
title = "dongjian's blog"
pygmentsUseClasses = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  logo = "img/avatar-icon.png"

[Author]
  name = "dongjian"
  email = "381423609@qq.com"
  facebook = "username"
  github = "dongjian"
  twitter = "dong381423609"
  linkedin = "pub/username/X/YYY/ZZZ"
  stackoverflow = "XXXXXXX/username"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "微博"
    url = "http://weibo.com/1769333170"
    weight = 2
