baseURL=                    "http://dongjian.github.io/"
disqusShortname = "dongjian"

title = "dongjian's blog"
author = "dongjian"
googleAnalytics="UA-50476358-2"
canonifyurls = true
paginate = 3
hasCJKLanguage=false
